---
config:
  flowchart:
    darkMode: true
    useMaxWidth: true
    curve: monotoneX
    htmlLabels: true
  theme: neo-dark
  look: handDrawn
---
flowchart LR
  subgraph Local ["`🏡&nbsp;Home&nbsp;Network`"]
    subgraph LAN ["`🤖&nbsp;Devices`"]
      direction LR
      R["`🌐&nbsp;Router`"]
      D["`💻&nbsp;Device`"]
      P["`📱&nbsp;Device`"]
    end
    subgraph HA ["`🏠&nbsp;Home&nbsp;Assistant`"]
      subgraph AO["`🌐&nbsp;Technitium&nbsp;DNS&nbsp;Server`"]
        DNS53["`DNS-over-UDP&NewLine;_Home&nbsp;Assistant&nbsp;IP_`"]
        F{"`dns_forwarders`"}
      end
    end
  end

  subgraph WAN ["`🌍&nbsp;Internet`"]
    subgraph CF ["`☁️&nbsp;Cloudflare`"]
      CFS53["`DNS-over-UDP&NewLine;_1.1.1.1_`"]
      CFSDoH["`DNS-over-HTTPS&NewLine;_https&colon;&sol;&sol;cloudflare-dns&period;com&sol;dns-query_`"]
      CFSDoT["`DNS-over-TLS&NewLine;_cloudflare-dns&period;com_`"]
    end
  end

  LAN --> |"`🔓&nbsp;DNS&nbsp;53&sol;UDP`"| DNS53
  DNS53 --> F
  F --> |"`🔓&nbsp;DNS&nbsp;53&sol;UDP`"| CFS53
  F --> |"`🔐&nbsp;DoH&nbsp;443&sol;TCP`"| CFSDoH
  F --> |"`🔐&nbsp;DoT&nbsp;853&sol;UDP`"| CFSDoT
