---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-ci.yaml@8c16988e4bff603298084d3ca89c461d2b8e42e5 # main
