---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-ci.yaml@f9d0d581cf6b61f7ee87760394c03a7374901883 # main
