# yamllint disable rule:line-length
---
name: "Clean up old packages"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  cleanup:
    name: "Clean up old untagged packages"
    runs-on: ubuntu-latest

    steps:
      - name: Delete old untagged versions of technitium-dns/amd64 package
        uses: actions/delete-package-versions@v5
        continue-on-error: true
        with:
          package-name: "technitium-dns/amd64"
          package-type: container
          min-versions-to-keep: 3
          ignore-versions: "^stable$|^beta$|^edge$|^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"

      - name: Delete old untagged versions of technitium-dns/aarch64 package
        uses: actions/delete-package-versions@v5
        continue-on-error: true
        with:
          package-name: "technitium-dns/aarch64"
          package-type: container
          min-versions-to-keep: 3
          ignore-versions: "^stable$|^beta$|^edge$|^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
