# yamllint disable rule:line-length
---
name: "Clean up old packages"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  cleanup:
    name: "Clean up old and untagged packages"
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: "addon-technitium-dns"
          package-type: "container"
          min-versions-to-keep: 1
          delete-only-untagged-versions: true
          owner: "staerk-ha-addons"
          token: ${{ secrets.DISPATCH_TOKEN }}
