# yamllint disable rule:line-length
---
name: "Clean up old packages"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  cleanup:
    name: "Clean up old and untagged packages"
    runs-on: ubuntu-latest

    steps:
      - name: Delete old package versions of technitium-dns/amd64
        uses: actions/delete-package-versions@v5
        continue-on-error: true
        with:
          package-name: "technitium-dns/amd64"
          package-type: container
          min-versions-to-keep: 0
          delete-only-untagged-versions: true
          owner: staerk-ha-addons
          token: ${{ secrets.CLEANUP_TOKEN }}
      - name: Delete old package versions of technitium-dns/aarch64
        uses: actions/delete-package-versions@v5
        continue-on-error: true
        with:
          package-name: "technitium-dns/aarch64"
          package-type: container
          min-versions-to-keep: 0
          delete-only-untagged-versions: true
          owner: staerk-ha-addons
          token: ${{ secrets.CLEANUP_TOKEN }}
