# yamllint disable rule:line-length
---
name: "Clean up old packages"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  cleanup:
    name: "Clean up old and untagged packages"
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v4
        with:
          # Target your addon package
          package-name: "addon-technitium-dns"
          package-type: "container"

          # Only delete versions with no tags (untagged)
          delete-only-untagged-versions: true

          # Optional: token with package:read and package:delete scopes
          token: ${{ secrets.GITHUB_TOKEN }}
