---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-deploy.yaml@8b2275cd2d23852a2c496b058449b2664fc70faf # main
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
