---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-deploy.yaml@71539f58a2dcb9c10b8f3500a270fcfb12dc7c08 # main
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
