---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-deploy.yaml@a2b2cb24f8172b6da0111cc9c246249ab3c2dfb1 # main
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
