---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/labels.yaml@255b50660f62bfbe2a37b67b558892903db74a66 # main
