---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/pr-labels.yaml@a7f5dd351b9f7cb10a71ed32bbad1f6243a97000 # main
