---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/pr-labels.yaml@dcf8cbb629dccbea059cb45661d0c871b900ab53 # main
