---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/pr-labels.yaml@f9d0d581cf6b61f7ee87760394c03a7374901883 # main
