---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/release-drafter.yaml@a2b2cb24f8172b6da0111cc9c246249ab3c2dfb1 # main
