---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  workflows:
    uses: staerk-ha-addons/workflows/.github/workflows/release-drafter.yaml@main
