---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/release-drafter.yaml@dcf8cbb629dccbea059cb45661d0c871b900ab53 # main
