---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/release-drafter.yaml@f9d0d581cf6b61f7ee87760394c03a7374901883 # main
