---
name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/stale.yaml@de69b49faca92bdbe7f4d8c5ad96f0699378b24d # main
