---
name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/stale.yaml@3df8e5b7f908b335001bc74ef5d05c313e9d5439 # main
